// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interprotocol.proto

package protocol.generate.internal;

public final class InterProtocol {
  private InterProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Dest}
   */
  public enum Dest
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>client = 1;</code>
     */
    client(1),
    /**
     * <code>authentication = 2;</code>
     */
    authentication(2),
    /**
     * <code>buslogin = 3;</code>
     */
    buslogin(3),
    /**
     * <code>reactor = 4;</code>
     */
    reactor(4),
    ;

    /**
     * <code>client = 1;</code>
     */
    public static final int client_VALUE = 1;
    /**
     * <code>authentication = 2;</code>
     */
    public static final int authentication_VALUE = 2;
    /**
     * <code>buslogin = 3;</code>
     */
    public static final int buslogin_VALUE = 3;
    /**
     * <code>reactor = 4;</code>
     */
    public static final int reactor_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Dest valueOf(int value) {
      return forNumber(value);
    }

    public static Dest forNumber(int value) {
      switch (value) {
        case 1: return client;
        case 2: return authentication;
        case 3: return buslogin;
        case 4: return reactor;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Dest>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Dest> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Dest>() {
            public Dest findValueByNumber(int number) {
              return Dest.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.generate.internal.InterProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final Dest[] VALUES = values();

    public static Dest valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Dest(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Dest)
  }

  public interface GTransferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GTransfer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Dest dest = 1;</code>
     */
    boolean hasDest();
    /**
     * <code>required .Dest dest = 1;</code>
     */
    protocol.generate.internal.InterProtocol.Dest getDest();

    /**
     * <code>optional uint64 netId = 2;</code>
     */
    boolean hasNetId();
    /**
     * <code>optional uint64 netId = 2;</code>
     */
    long getNetId();

    /**
     * <code>required string userId = 3;</code>
     */
    boolean hasUserId();
    /**
     * <code>required string userId = 3;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>required string userId = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>required uint32 ptoNum = 4;</code>
     */
    boolean hasPtoNum();
    /**
     * <code>required uint32 ptoNum = 4;</code>
     */
    int getPtoNum();

    /**
     * <code>required bytes msg = 5;</code>
     */
    boolean hasMsg();
    /**
     * <code>required bytes msg = 5;</code>
     */
    com.google.protobuf.ByteString getMsg();
  }
  /**
   * <pre>
   *服务内部转换协议
   * </pre>
   *
   * Protobuf type {@code GTransfer}
   */
  public  static final class GTransfer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GTransfer)
      GTransferOrBuilder {
    // Use GTransfer.newBuilder() to construct.
    private GTransfer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GTransfer() {
      dest_ = 1;
      netId_ = 0L;
      userId_ = "";
      ptoNum_ = 0;
      msg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GTransfer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.generate.internal.InterProtocol.Dest value = protocol.generate.internal.InterProtocol.Dest.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dest_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              netId_ = input.readUInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              userId_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ptoNum_ = input.readUInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.generate.internal.InterProtocol.internal_static_GTransfer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.generate.internal.InterProtocol.internal_static_GTransfer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.generate.internal.InterProtocol.GTransfer.class, protocol.generate.internal.InterProtocol.GTransfer.Builder.class);
    }

    private int bitField0_;
    public static final int DEST_FIELD_NUMBER = 1;
    private int dest_;
    /**
     * <code>required .Dest dest = 1;</code>
     */
    public boolean hasDest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Dest dest = 1;</code>
     */
    public protocol.generate.internal.InterProtocol.Dest getDest() {
      protocol.generate.internal.InterProtocol.Dest result = protocol.generate.internal.InterProtocol.Dest.valueOf(dest_);
      return result == null ? protocol.generate.internal.InterProtocol.Dest.client : result;
    }

    public static final int NETID_FIELD_NUMBER = 2;
    private long netId_;
    /**
     * <code>optional uint64 netId = 2;</code>
     */
    public boolean hasNetId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 netId = 2;</code>
     */
    public long getNetId() {
      return netId_;
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object userId_;
    /**
     * <code>required string userId = 3;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string userId = 3;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PTONUM_FIELD_NUMBER = 4;
    private int ptoNum_;
    /**
     * <code>required uint32 ptoNum = 4;</code>
     */
    public boolean hasPtoNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 ptoNum = 4;</code>
     */
    public int getPtoNum() {
      return ptoNum_;
    }

    public static final int MSG_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>required bytes msg = 5;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes msg = 5;</code>
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPtoNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, dest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, netId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, ptoNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, msg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, netId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, ptoNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.generate.internal.InterProtocol.GTransfer)) {
        return super.equals(obj);
      }
      protocol.generate.internal.InterProtocol.GTransfer other = (protocol.generate.internal.InterProtocol.GTransfer) obj;

      boolean result = true;
      result = result && (hasDest() == other.hasDest());
      if (hasDest()) {
        result = result && dest_ == other.dest_;
      }
      result = result && (hasNetId() == other.hasNetId());
      if (hasNetId()) {
        result = result && (getNetId()
            == other.getNetId());
      }
      result = result && (hasUserId() == other.hasUserId());
      if (hasUserId()) {
        result = result && getUserId()
            .equals(other.getUserId());
      }
      result = result && (hasPtoNum() == other.hasPtoNum());
      if (hasPtoNum()) {
        result = result && (getPtoNum()
            == other.getPtoNum());
      }
      result = result && (hasMsg() == other.hasMsg());
      if (hasMsg()) {
        result = result && getMsg()
            .equals(other.getMsg());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDest()) {
        hash = (37 * hash) + DEST_FIELD_NUMBER;
        hash = (53 * hash) + dest_;
      }
      if (hasNetId()) {
        hash = (37 * hash) + NETID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNetId());
      }
      if (hasUserId()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId().hashCode();
      }
      if (hasPtoNum()) {
        hash = (37 * hash) + PTONUM_FIELD_NUMBER;
        hash = (53 * hash) + getPtoNum();
      }
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.generate.internal.InterProtocol.GTransfer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.generate.internal.InterProtocol.GTransfer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.generate.internal.InterProtocol.GTransfer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.generate.internal.InterProtocol.GTransfer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.generate.internal.InterProtocol.GTransfer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.generate.internal.InterProtocol.GTransfer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.generate.internal.InterProtocol.GTransfer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.generate.internal.InterProtocol.GTransfer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.generate.internal.InterProtocol.GTransfer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.generate.internal.InterProtocol.GTransfer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.generate.internal.InterProtocol.GTransfer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.generate.internal.InterProtocol.GTransfer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.generate.internal.InterProtocol.GTransfer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *服务内部转换协议
     * </pre>
     *
     * Protobuf type {@code GTransfer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GTransfer)
        protocol.generate.internal.InterProtocol.GTransferOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.generate.internal.InterProtocol.internal_static_GTransfer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.generate.internal.InterProtocol.internal_static_GTransfer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.generate.internal.InterProtocol.GTransfer.class, protocol.generate.internal.InterProtocol.GTransfer.Builder.class);
      }

      // Construct using protocol.generate.internal.InterProtocol.GTransfer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        dest_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        netId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ptoNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        msg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.generate.internal.InterProtocol.internal_static_GTransfer_descriptor;
      }

      public protocol.generate.internal.InterProtocol.GTransfer getDefaultInstanceForType() {
        return protocol.generate.internal.InterProtocol.GTransfer.getDefaultInstance();
      }

      public protocol.generate.internal.InterProtocol.GTransfer build() {
        protocol.generate.internal.InterProtocol.GTransfer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.generate.internal.InterProtocol.GTransfer buildPartial() {
        protocol.generate.internal.InterProtocol.GTransfer result = new protocol.generate.internal.InterProtocol.GTransfer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dest_ = dest_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.netId_ = netId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ptoNum_ = ptoNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.generate.internal.InterProtocol.GTransfer) {
          return mergeFrom((protocol.generate.internal.InterProtocol.GTransfer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.generate.internal.InterProtocol.GTransfer other) {
        if (other == protocol.generate.internal.InterProtocol.GTransfer.getDefaultInstance()) return this;
        if (other.hasDest()) {
          setDest(other.getDest());
        }
        if (other.hasNetId()) {
          setNetId(other.getNetId());
        }
        if (other.hasUserId()) {
          bitField0_ |= 0x00000004;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasPtoNum()) {
          setPtoNum(other.getPtoNum());
        }
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDest()) {
          return false;
        }
        if (!hasUserId()) {
          return false;
        }
        if (!hasPtoNum()) {
          return false;
        }
        if (!hasMsg()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.generate.internal.InterProtocol.GTransfer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.generate.internal.InterProtocol.GTransfer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int dest_ = 1;
      /**
       * <code>required .Dest dest = 1;</code>
       */
      public boolean hasDest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Dest dest = 1;</code>
       */
      public protocol.generate.internal.InterProtocol.Dest getDest() {
        protocol.generate.internal.InterProtocol.Dest result = protocol.generate.internal.InterProtocol.Dest.valueOf(dest_);
        return result == null ? protocol.generate.internal.InterProtocol.Dest.client : result;
      }
      /**
       * <code>required .Dest dest = 1;</code>
       */
      public Builder setDest(protocol.generate.internal.InterProtocol.Dest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dest_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Dest dest = 1;</code>
       */
      public Builder clearDest() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dest_ = 1;
        onChanged();
        return this;
      }

      private long netId_ ;
      /**
       * <code>optional uint64 netId = 2;</code>
       */
      public boolean hasNetId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 netId = 2;</code>
       */
      public long getNetId() {
        return netId_;
      }
      /**
       * <code>optional uint64 netId = 2;</code>
       */
      public Builder setNetId(long value) {
        bitField0_ |= 0x00000002;
        netId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 netId = 2;</code>
       */
      public Builder clearNetId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        netId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>required string userId = 3;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string userId = 3;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userId = 3;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 3;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 3;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }

      private int ptoNum_ ;
      /**
       * <code>required uint32 ptoNum = 4;</code>
       */
      public boolean hasPtoNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 ptoNum = 4;</code>
       */
      public int getPtoNum() {
        return ptoNum_;
      }
      /**
       * <code>required uint32 ptoNum = 4;</code>
       */
      public Builder setPtoNum(int value) {
        bitField0_ |= 0x00000008;
        ptoNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 ptoNum = 4;</code>
       */
      public Builder clearPtoNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ptoNum_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes msg = 5;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes msg = 5;</code>
       */
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>required bytes msg = 5;</code>
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes msg = 5;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GTransfer)
    }

    // @@protoc_insertion_point(class_scope:GTransfer)
    private static final protocol.generate.internal.InterProtocol.GTransfer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.generate.internal.InterProtocol.GTransfer();
    }

    public static protocol.generate.internal.InterProtocol.GTransfer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GTransfer>
        PARSER = new com.google.protobuf.AbstractParser<GTransfer>() {
      public GTransfer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GTransfer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GTransfer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GTransfer> getParserForType() {
      return PARSER;
    }

    public protocol.generate.internal.InterProtocol.GTransfer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GreetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Greet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Greet.From from = 1;</code>
     */
    boolean hasFrom();
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    protocol.generate.internal.InterProtocol.Greet.From getFrom();
  }
  /**
   * <pre>
   *各个服务间建立连接的时候发送的握手协议
   * </pre>
   *
   * Protobuf type {@code Greet}
   */
  public  static final class Greet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Greet)
      GreetOrBuilder {
    // Use Greet.newBuilder() to construct.
    private Greet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Greet() {
      from_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Greet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.generate.internal.InterProtocol.Greet.From value = protocol.generate.internal.InterProtocol.Greet.From.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                from_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.generate.internal.InterProtocol.internal_static_Greet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.generate.internal.InterProtocol.internal_static_Greet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.generate.internal.InterProtocol.Greet.class, protocol.generate.internal.InterProtocol.Greet.Builder.class);
    }

    /**
     * Protobuf enum {@code Greet.From}
     */
    public enum From
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>buslogin = 1;</code>
       */
      buslogin(1),
      /**
       * <code>reactor = 2;</code>
       */
      reactor(2),
      /**
       * <code>authentication = 3;</code>
       */
      authentication(3),
      ;

      /**
       * <code>buslogin = 1;</code>
       */
      public static final int buslogin_VALUE = 1;
      /**
       * <code>reactor = 2;</code>
       */
      public static final int reactor_VALUE = 2;
      /**
       * <code>authentication = 3;</code>
       */
      public static final int authentication_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static From valueOf(int value) {
        return forNumber(value);
      }

      public static From forNumber(int value) {
        switch (value) {
          case 1: return buslogin;
          case 2: return reactor;
          case 3: return authentication;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<From>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          From> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<From>() {
              public From findValueByNumber(int number) {
                return From.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.generate.internal.InterProtocol.Greet.getDescriptor().getEnumTypes().get(0);
      }

      private static final From[] VALUES = values();

      public static From valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private From(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Greet.From)
    }

    private int bitField0_;
    public static final int FROM_FIELD_NUMBER = 1;
    private int from_;
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    public protocol.generate.internal.InterProtocol.Greet.From getFrom() {
      protocol.generate.internal.InterProtocol.Greet.From result = protocol.generate.internal.InterProtocol.Greet.From.valueOf(from_);
      return result == null ? protocol.generate.internal.InterProtocol.Greet.From.buslogin : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, from_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, from_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.generate.internal.InterProtocol.Greet)) {
        return super.equals(obj);
      }
      protocol.generate.internal.InterProtocol.Greet other = (protocol.generate.internal.InterProtocol.Greet) obj;

      boolean result = true;
      result = result && (hasFrom() == other.hasFrom());
      if (hasFrom()) {
        result = result && from_ == other.from_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFrom()) {
        hash = (37 * hash) + FROM_FIELD_NUMBER;
        hash = (53 * hash) + from_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.generate.internal.InterProtocol.Greet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.generate.internal.InterProtocol.Greet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.generate.internal.InterProtocol.Greet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.generate.internal.InterProtocol.Greet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.generate.internal.InterProtocol.Greet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.generate.internal.InterProtocol.Greet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.generate.internal.InterProtocol.Greet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.generate.internal.InterProtocol.Greet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.generate.internal.InterProtocol.Greet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.generate.internal.InterProtocol.Greet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.generate.internal.InterProtocol.Greet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.generate.internal.InterProtocol.Greet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.generate.internal.InterProtocol.Greet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *各个服务间建立连接的时候发送的握手协议
     * </pre>
     *
     * Protobuf type {@code Greet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Greet)
        protocol.generate.internal.InterProtocol.GreetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.generate.internal.InterProtocol.internal_static_Greet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.generate.internal.InterProtocol.internal_static_Greet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.generate.internal.InterProtocol.Greet.class, protocol.generate.internal.InterProtocol.Greet.Builder.class);
      }

      // Construct using protocol.generate.internal.InterProtocol.Greet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        from_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.generate.internal.InterProtocol.internal_static_Greet_descriptor;
      }

      public protocol.generate.internal.InterProtocol.Greet getDefaultInstanceForType() {
        return protocol.generate.internal.InterProtocol.Greet.getDefaultInstance();
      }

      public protocol.generate.internal.InterProtocol.Greet build() {
        protocol.generate.internal.InterProtocol.Greet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.generate.internal.InterProtocol.Greet buildPartial() {
        protocol.generate.internal.InterProtocol.Greet result = new protocol.generate.internal.InterProtocol.Greet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.from_ = from_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.generate.internal.InterProtocol.Greet) {
          return mergeFrom((protocol.generate.internal.InterProtocol.Greet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.generate.internal.InterProtocol.Greet other) {
        if (other == protocol.generate.internal.InterProtocol.Greet.getDefaultInstance()) return this;
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFrom()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.generate.internal.InterProtocol.Greet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.generate.internal.InterProtocol.Greet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int from_ = 1;
      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public protocol.generate.internal.InterProtocol.Greet.From getFrom() {
        protocol.generate.internal.InterProtocol.Greet.From result = protocol.generate.internal.InterProtocol.Greet.From.valueOf(from_);
        return result == null ? protocol.generate.internal.InterProtocol.Greet.From.buslogin : result;
      }
      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public Builder setFrom(protocol.generate.internal.InterProtocol.Greet.From value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        from_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = 1;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Greet)
    }

    // @@protoc_insertion_point(class_scope:Greet)
    private static final protocol.generate.internal.InterProtocol.Greet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.generate.internal.InterProtocol.Greet();
    }

    public static protocol.generate.internal.InterProtocol.Greet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Greet>
        PARSER = new com.google.protobuf.AbstractParser<Greet>() {
      public Greet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Greet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Greet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Greet> getParserForType() {
      return PARSER;
    }

    public protocol.generate.internal.InterProtocol.Greet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GTransfer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GTransfer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Greet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Greet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023interprotocol.proto\"\\\n\tGTransfer\022\023\n\004de" +
      "st\030\001 \002(\0162\005.Dest\022\r\n\005netId\030\002 \001(\004\022\016\n\006userId" +
      "\030\003 \002(\t\022\016\n\006ptoNum\030\004 \002(\r\022\013\n\003msg\030\005 \002(\014\"Y\n\005G" +
      "reet\022\031\n\004from\030\001 \002(\0162\013.Greet.From\"5\n\004From\022" +
      "\014\n\010buslogin\020\001\022\013\n\007reactor\020\002\022\022\n\016authentica" +
      "tion\020\003*A\n\004Dest\022\n\n\006client\020\001\022\022\n\016authentica" +
      "tion\020\002\022\014\n\010buslogin\020\003\022\013\n\007reactor\020\004B+\n\032pro" +
      "tocol.generate.internalB\rInterProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GTransfer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GTransfer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GTransfer_descriptor,
        new java.lang.String[] { "Dest", "NetId", "UserId", "PtoNum", "Msg", });
    internal_static_Greet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Greet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Greet_descriptor,
        new java.lang.String[] { "From", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
